language: php
php:
  - 7.3
before_script:
  - cp .env.travis .env
  - mkdir -p database
  - touch database/database.sqlite
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --no-interaction -vvv

script:
  - php artisan test
